djstarter/demo_app/urls.py
from django.urls import path
from . import views

app_name = 'demo_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='demo-index'),
    # ex: /demo_app/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /demo_app/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /demo_app/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

djstarter/djstarter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('demo_app/', include('demo_app.urls')),
    path('admin/', admin.site.urls),
]

djstarter/demo_app/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

djstarter/demo_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'demo_app/index.html', context)


class IndexView(generic.ListView):
    template_name = 'demo_app/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'demo_app/detail.html', {'question': question})


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'demo_app/detail.html', {'question': question})


class DetailView(generic.DetailView):
    model = Question
    template_name = 'demo_app/detail.html'


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'demo_app/results.html', {'question': question})


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'demo_app/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'demo_app/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('demo_app:results', args=(question.id,)))

djstarter/demo_app/templates/demo_app/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'demo_app:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<br/>
<input type="submit" value="Vote">
</form>

djstarter/demo_app/templates/demo_app/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'demo_app/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'demo_app:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions are available.</p>
{% endif %}

djstarter/demo_app/templates/demo_app/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'demo_app:detail' question.id %}">Vote again?</a>